version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-19-114-27.compute-1.amazonaws.com
            database: d10gsi4dp0pknm
            # schema: public
            user: sjprimfrqhdgqd
            password: 7ec9d3e6ac577b3197428989023ccfa7fb58bdb439850580751fab82828e8663
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true